In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
mnist = pd.read_csv("./Data/train.csv")
mnist.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [3]:
x_data = mnist.drop("label", axis=1)
x_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [4]:
# normalize pixel values
x_data = x_data / 255
x_data.iloc[:1,:].values.max()

1.0

In [5]:
y_labels = mnist["label"]
y_labels.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [6]:
y_labels = pd.get_dummies(y_labels)

In [7]:
x_train = np.array(x_data.iloc[:35000, :].values)
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
x_validation = np.array(x_data.iloc[35000:40000,:].values)
x_validation.shape

(5000, 784)

In [9]:
x_test = np.array(x_data.iloc[40000:,:].values)
x_test.shape

(2000, 784)

In [10]:
y_train = y_labels[:35000].values
y_train.shape

(35000, 10)

In [11]:
y_validation = y_labels[35000:40000].values
y_validation.shape

(5000, 10)

In [12]:
y_test = y_labels[40000:].values
y_validation.shape

(5000, 10)

In [13]:
#placeholders
x = tf.placeholder(tf.float32, shape=[None, 784])
y_true = tf.placeholder(tf.float32, shape=[None, 10])

In [14]:
# We only have 2 layers so we are going to use from 784 to 10 which is our output
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

In [15]:
y = tf.matmul(x, W) + b

In [16]:
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_true, logits=y))

In [17]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)

In [18]:
train = optimizer.minimize(cross_entropy)

In [19]:
init = tf.global_variables_initializer()

In [20]:
saver = tf.train.Saver()

In [21]:
with tf.Session() as sess:
    sess.run(init)
    
    batch_size = 100
    
    for step in range(10000):
        rand_ind = np.random.randint(len(x_train), size=batch_size)
        feed = {x:x_train[rand_ind], y_true:y_train[rand_ind]}
        sess.run(train, feed_dict=feed)
    
    # Evaluate the model
    correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_true,1))
    acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print(sess.run(acc, feed_dict={x:x_validation, y_true:y_validation}))
    
    saver.save(sess, "perfect_model/good_accuracy.ckpy")

0.926


In [24]:
test_data = pd.read_csv("./Data/test.csv")
test_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [25]:
test_data.iloc[0:1,:].values.max()

255

In [26]:
test_data = test_data / 255

In [27]:
test_data.iloc[0:1,:].values.max()

1.0

In [28]:
test_data = test_data.values
test_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
test_data.shape

(28000, 784)

In [30]:
with tf.Session() as sess:
    saver.restore(sess, "perfect_model/good_accuracy.ckpy")
    ##
    # to use tensorboard you need to have a file writer to keep the logs
    #train_writer = tf.summary.FileWriter("./tensorboard/train", graph=tf.get_default_graph())
    #validation_writer = tf.summary.FileWriter("./tensorboard/validation", graph=tf.get_default_graph())
    ##
    prediction = y
    predictions = sess.run(prediction, feed_dict={x:test_data})
    result = []
    decode = tf.argmax(predictions, axis=1)
    result = sess.run(decode)
    print (result)

INFO:tensorflow:Restoring parameters from perfect_model/good_accuracy.ckpy
[2 0 9 ... 3 9 2]


In [31]:
result_df = pd.DataFrame(result, columns=["Label"], dtype=int)
result_df.index +=1

In [32]:
result_df.index.name = "ImageId"

In [33]:
result_df.head()

Label
ImageId       
1            2
2            0
3            9
4            7
5            3

In [34]:
result_df.to_csv("./results.csv")

In [ ]:
#for tensorboard on terminal home directory
# tensorboard --logdir=./tensorboard 